### ISSUE TITLE
Requesting Docs for H2O Experiment Tracking

### ISSUE THREAD

**Issue by rasika** [h2oai/haic-doc-issues-requests#2]
We have created [gdoc](https://docs.google.com/document/d/1StZHDk9U-qUElXjxX49-KKqF6WWYnvARWhr7o_tcG0g/edit#heading=h.lrdk42wd089f) to create the basic structure of the docs.

Would appreciate allocating a docs team member to work on these docs.

**Comment by sherenem** [comment]
https://docs.h2o.ai/h2o-experiment-tracking/
