### ISSUE TITLE
[HAIC-APP] A Minor grammatical Typo in the documentation

### ISSUE THREAD

**Issue by parulnith** [h2oai/haic-doc-issues-requests#3]
### Documentation issue/request
A Minor grammatical Typo in the documentation

### Additional context

Missing space in the following subtitle between **a** and **dataset**, on the page(details mentioned below):

> Validation tests for `adataset:`

It should be 
> Validation tests for a dataset:

### Page details 

- Application name: H2O Model Security
- Application version: v0.15.0
- Page title: /wave-apps/h2o-model-validation/guide/tests/supported-validation-tests/

**Comment by 5675sp** [comment]
Hello @parulnith,

Thank you! The error has been corrected, and live docs have been updated. 

Best regards, 
Sergio Perez
